name: image-gen

services:
  app:
    image: ghcr.io/invoke-ai/invokeai
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./data:/invokeai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
